openapi: 3.0.2
info:
  title: GA4GH Service Registry API Specification
  version: 1.0.0
  description: 'More information on [GitHub](https://github.com/ga4gh-discovery/ga4gh-service-registry/).'
  license:
    name: Apache 2.0
    url: 'https://raw.githubusercontent.com/ga4gh-discovery/ga4gh-service-registry/develop/LICENSE'
  contact:
    name: GA4GH Discovery Networks Team
    email: ga4gh-discovery-networks@ga4gh.org
security:
  - authToken: []
paths:
  /services:
    get:
      tags:
        - services
      summary: Get page of services
      parameters:
        - name: page
          in: query
          description: Page token
          required: false
          schema:
            type: string
            example: 'NDMyNzQyODI3OTQw'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/Service'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'
  /services/types:
    get:
      tags:
        - services
      summary: List known service types
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: 'org.ga4gh:beacon:1.0.1'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'
  '/services/{serviceId}':
    get:
      tags:
        - services
      summary: Get service specified by identifier
      parameters:
        - name: serviceId
          in: path
          description: Service identifier
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'
components:
  securitySchemes:
    authToken:
      description: |
        A valid authorization token must be passed in the 'Authorization' header.
        Example syntax for using 'Authorization' header :
          Bearer: token_string
      type: apiKey
      name: Authorization
      in: header
  responses:
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServerError:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Service:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/ga4gh-discovery/ga4gh-service-info/develop/service-info.yaml#/components/schemas/ServiceInfo'
        - type: object
          properties:
            url:
              type: string
              format: uri
              example: 'https://ga4gh-example-service.com'
          required:
            - url
    Pagination:
      type: object
      properties:
        previousPage:
          type: string
          format: uri
          example: 'https://ga4gh-example-service.com?page=dXNlcjpVMEc5V0ZYTlo'
        nextPage:
          type: string
          format: uri
          example: 'https://ga4gh-example-service.com?page=NDMyNzQyODI3OTQw'
    Error:
      type: object
      properties:
        code:
          type: integer
          description: HTTP status code
          example: '400'
        message:
          type: string
          description: Description of the error or information.
          example: 'Bad request'
        timestamp:
          type: string
          format: date-time
          description: Timestamp of service modification in RFC 3339.
          example: '2019-06-04T12:58:19Z'
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
                description: Code
                example: 'IllegalArgumentException'
              message:
                type: string
                description: Description of the error or information.
                example: 'Argument x must be greater than zero'
